nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)
    documentation:
        info:
            title: Social Network API Doc
            description: Social Network using Symfony framework
            version: 1.0.1
        securityDefinitions:
            ApiAuth:
                type: apiKey
                in: header
                name: x-api-key
        paths:
            /api/user/login:
                post:
                    tags:
                        - User API
                    description: Login into the api
                    produces:
                        - application/json
                    parameters:
                        - name: user
                          description: User object used for user authentication
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  email:
                                      type: string
                                      example: moroztaras@i.ua
                                  plainPassword:
                                      type: string
                                      example: moroztaras
                    responses:
                        '200':
                            description: Login successful. Returns user profile
                            schema:
                                type: object
                                properties:
                                    id:
                                      type: integer
                                      example: 1
                                    fullName:
                                      type: string
                                      example: Moroz Taras
                                    email:
                                      type: string
                                      example: moroztaras@i.ua
                                    gender:
                                      type: string
                                      example: m
                                    country:
                                      type: string
                                      example: UA
                                    birthday:
                                      type: string
                                      example: "1986-07-15T00:00:00+02:00"
                                    create_at:
                                      type: string
                                      example: "2019-03-27T14:02:29+02:00"
                                    update_at:
                                      type: string
                                      example: "2019-03-27T14:02:29+02:00"
                                    status:
                                      type: integer
                                      example: 1
                                    roles:
                                      type: string
                                      example: "USER_ROLE"
                                    api-token:
                                        type: string
                                        example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
                        '400':
                            description: Authentication error
            /api/user/registration:
                post:
                    tags:
                        - User API
                    description: Registration new user
                    produces:
                        - application/json
                    parameters:
                        - name: user
                          description: User to be registered
                          in: body
                          required: true
                          schema:
                              type: object
                              properties:
                                  fullName:
                                      type: string
                                      example: new_fake_fullName
                                  email:
                                      type: string
                                      example: new_fake_mail@mail.ua
                                  plainPassword:
                                      type: string
                                      example: fake_password
                                  gender:
                                      type: string
                                      example: m
                                  region:
                                      type: string
                                      example: UA
                                  birthday:
                                      type: string
                                      example: "1986-07-15T00:00:00+02:00"
                    responses:
                        '200':
                            description: Registration successful
                            schema:
                                type: object
                                properties:
                                    id:
                                      type: string
                                      example: 1
                                    fullName:
                                      type: string
                                      example: new_fake_fullName
                                    email:
                                      type: string
                                      example: email@mail.ua
                                    gender:
                                      type: string
                                      example: m
                                    country:
                                      type: string
                                      example: UA
                                    birthday:
                                      type: string
                                      example: "1986-07-15T00:00:00+02:00"
                                    create_at:
                                      type: string
                                      example: "2019-03-27T14:02:29+02:00"
                                    update_at:
                                      type: string
                                      example: "2019-03-27T14:02:29+02:00"
                                    status:
                                      type: integer
                                      example: 1
                                    roles:
                                      type: string
                                      example: "USER_ROLE"
                                    api-token:
                                        type: string
                                        example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
                        '400':
                            description: Bad request
            /api/user/profile:
                get:
                    tags:
                        - User API
                    description: My profile user into the api
                    produces:
                        - application/json
                    parameters:
                        - name:  x-api-key
                          description: X-API-KEY
                          in: header
                          required: true
                    responses:
                        '200':
                            description: Returns my profile user
                            schema:
                                type: object
                                properties:
                                    id:
                                      type: string
                                      example: 1
                                    fullName:
                                      type: string
                                      example: new_fake_fullName
                                    email:
                                      type: string
                                      example: email@mail.ua
                                    gender:
                                      type: string
                                      example: m
                                    country:
                                      type: string
                                      example: UA
                                    birthday:
                                      type: string
                                      example: "1986-07-15T00:00:00+02:00"
                                    create_at:
                                      type: string
                                      example: "2019-03-27T14:02:29+02:00"
                                    update_at:
                                      type: string
                                      example: "2019-03-27T14:02:29+02:00"
                                    status:
                                      type: integer
                                      example: 1
                                    roles:
                                      type: string
                                      example: "USER_ROLE"
                                    api-token:
                                        type: string
                                        example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
                        '400':
                            description: Authentication error
            /api/user/{id}/profile:
                get:
                    tags:
                        - User API
                    description: Profile user into the api
                    produces:
                        - application/json
                    parameters:
                        - name: id
                          description: User ID
                          in: path
                          required: true
                          type: string
                    responses:
                        '200':
                            description: Returns user profile
                            schema:
                                type: object
                                properties:
                                    id:
                                      type: string
                                      example: 1
                                    fullName:
                                      type: string
                                      example: new_fake_fullName
                                    email:
                                      type: string
                                      example: email@mail.ua
                                    gender:
                                      type: string
                                      example: m
                                    country:
                                      type: string
                                      example: UA
                                    birthday:
                                      type: string
                                      example: "1986-07-15T00:00:00+02:00"
                                    create_at:
                                      type: string
                                      example: "2019-03-27T14:02:29+02:00"
                                    update_at:
                                      type: string
                                      example: "2019-03-27T14:02:29+02:00"
                                    status:
                                      type: integer
                                      example: 1
                                    roles:
                                      type: string
                                      example: "USER_ROLE"
                        '404':
                            description: User object not found
