#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_logout:
  path: /logout

login_check:
    path: /login_check

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
